language: node_js
node_js:
  - 'node'
cache:
  directories:
    - ~/.npm
stages:
  - test
  - name: release
    if: branch = master AND repo = eventOneHQ/cordova-utils AND type != pull_request
jobs:
  include:
    - stage: test
      node_js: lts/*
      before_script:
        - npm run download
      script:
        - npm run test
        - npm run docs
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GH_TOKEN
        local-dir: out
        on:
          branch: master
          repo: eventOneHQ/cordova-utils
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
notifications:
  email: false
